### ISSUE TITLE
Update README to link to both the GitHub repo and the Docker Hub entry

### ISSUE THREAD

**Issue by RichardBronosky** [thinca/dockerfile-vim#1]
Luckily your username is the same in both places so it wasn't hard to find this repo. However, users who find a container like https://hub.docker.com/r/thinca/vim should always check the source before running it, and there is no link to this repo or the Dockerfile that can be found there.

**Comment by thinca** [comment]
I updated [the README on Docker Hub](https://hub.docker.com/r/thinca/vim).
